// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGcFE1SRKVAtA44_PjYsg3R5dYFX2oN7o',
    appId: '1:320993770464:web:e99e2017cac1c2ce20c985',
    messagingSenderId: '320993770464',
    projectId: 'green-predict',
    authDomain: 'green-predict.firebaseapp.com',
    storageBucket: 'green-predict.firebasestorage.app',
    measurementId: 'G-F5DFV3SB7L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGcFE1SRKVAtA44_PjYsg3R5dYFX2oN7o',
    appId: '1:320993770464:android:239e358f9b827afc20c985',
    messagingSenderId: '320993770464',
    projectId: 'green-predict',
    storageBucket: 'green-predict.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGcFE1SRKVAtA44_PjYsg3R5dYFX2oN7o',
    appId: '1:320993770464:ios:239e358f9b827afc20c985',
    messagingSenderId: '320993770464',
    projectId: 'green-predict',
    storageBucket: 'green-predict.firebasestorage.app',
    iosBundleId: 'com.example.flutterapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGcFE1SRKVAtA44_PjYsg3R5dYFX2oN7o',
    appId: '1:320993770464:ios:239e358f9b827afc20c985',
    messagingSenderId: '320993770464',
    projectId: 'green-predict',
    storageBucket: 'green-predict.firebasestorage.app',
    iosBundleId: 'com.example.flutterapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBGcFE1SRKVAtA44_PjYsg3R5dYFX2oN7o',
    appId: '1:320993770464:web:e99e2017cac1c2ce20c985',
    messagingSenderId: '320993770464',
    projectId: 'green-predict',
    authDomain: 'green-predict.firebaseapp.com',
    storageBucket: 'green-predict.firebasestorage.app',
    measurementId: 'G-F5DFV3SB7L',
  );
}
